name: Deploy Gatsby app to Github Pages

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - master

jobs:
  build-deploy:
#    runs-on: node:10-alpine
    steps:
      - uses: actions/checkout@master
        
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          
      - name: Install dependencies
        run: yarn install

      - name: Build site for deploy
        run: yarn run build

      - name: Deploy github pages
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
