name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Install PHP Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      
      - name: Tests
        run: ./vendor/bin/pest --ci
        
      - name: Upload test screen shots
        uses: actions/upload-artifact@v4
        with:
          name: browser-screen-shots
          path: "./tests/Browser/Screenshots"


    

    

    
